apiVersion: v1
kind: BuildConfig
metadata:
  name: yogendrasri.inventory-updated-management-bff-yks
  labels:
    app: inventory-updated-management-bff-yks
spec:
  triggers:
    - type: GitHub
      github:
        secret: secret101
  source:
    git:
      uri: 'https://github.com/yogendrasri/inventory-updated-management-bff-yks.git'
      ref: master
  strategy:
    jenkinsPipelineStrategy:
      jenkinsfilePath: Jenkinsfile
      env:
        - name: CLOUD_NAME
          value: openshift
        - name: NAMESPACE
          value: dev-yks
        - name: BRANCH
          value: master
